title: "Hướng Dẫn Markdown"
url: https://oevietnam.github.io/ # site url
baseurl: "/markdown-vietnamese" # apply repo name if use it under gh-pages branch

repo: https://oevietnam.github.io/markdown-vietnamese
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap

collections:
  basic-syntax:
  extended-syntax:
  tools:
    output: true
    permalink: /tools/:title/

defaults:
  - scope:
      type: tools
    values:
      layout: tool

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name     : "Matt Cone"

# social settings
og_locale: "vi_VN"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile", "netlify.toml", "deploy.sh", "redirects.conf"]
